### PR TITLE
feat(deps): upgrade intercom sdk

### PR DESCRIPTION
**Pull request by Oupsla**
BREAKING CHANGE: androidX build needed + iOs 10

### CODE REVIEW

**Comment by florianlauer** [comment]
What new features does it bring ?

**Comment by Oupsla** [comment]
Banners and compatibility with androidX  😄

**Comment by florianlauer** [comment]
Is it normal that there are changes in `package-lock.json` but not in `package.json` ? Maybe the `package-lock.json` was not commited last time ?

**Comment by Oupsla** [comment]
> Is it normal that there are changes in `package-lock.json` but not in `package.json` ? Maybe the `package-lock.json` was not commited last time ?

Yes I have make a `npm i` in the root folder that have edited the package-lock, I think it is only minor versions

**Pull request merged**
